### ISSUE TITLE
feature want: close log print and print the duplicate result to stdout

### ISSUE THREAD

**Issue by alingse** [m-manu/go-find-duplicates#10]
I want to do some auto remove duplicate tools

here is what I do now
```bash
go-find-duplicates -o json -m 0 ./
cat duplicates_230506_2340187.json|jq '.[]|.paths[1:]|.[]'|xargs -I {} rm {}
```
I want use `-q` or other flag to quite the running log  and just print the duplicate result to stdout

there is two pros
1.  we can use pipe to combine the command
2. there is no extra output file if i run this in current dir `./`

```bash
go-find-duplicates -o json -m 0 ./ -q|jq '.[]|.paths[1:]|.[]'|xargs -I {} rm {}
```

**Comment by alingse** [comment]
@m-manu if you think it was ok, I would like to post a pr for it.

**Comment by m-manu** [comment]
That's a great idea! Please send PR. 

Now, would an additional `-q` flag make sense or would a new output type itself? 🤔
