### ISSUE TITLE
GNU command line option conventions

### ISSUE THREAD

**Issue by mario-grgic** [m-manu/go-find-duplicates#4]
First of all, I love the tool, thank you for creating it. Very useful and helped me discover a whole slew of duplicates in my library. 

However, my only small gripe is that the tool does not use typical[ POSIX convention ](https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html)when it comes to command line options (single - for short options, -- for long options). This it makes it stand out from most of other UNIX tools.

**Comment by m-manu** [comment]
Thanks for the kind words. It was bothering me that Golang SDK's `flag` package doesn't follow POSIX convention. Couldn't find a good alternative (something that's well maintained, production-grade and easy to migrate). The closest I could get was this: https://github.com/ogier/pflag

**Comment by mario-grgic** [comment]
There is also 

https://github.com/spf13/cobra 

used by Kubernetes, Github or Istio and has some interesting features such as intelligent suggestions, automatic help generation, documentation, shell autocompletion, it is POSIX compliant, etc.

**Comment by m-manu** [comment]
@mario-grgic This is implemented in `v1.3.0`

**Comment by m-manu** [comment]
@mario-grgic This is implemented in `v1.3.0`
