### ISSUE TITLE
Sorting output results by file size

### ISSUE THREAD

**Issue by sanjosanjo** [m-manu/go-find-duplicates#9]
I love this tool!  The thing I'm trying to figure out is how I could write a script to sort the resulting output file to put the results in order from largest to smallest files - so I know which ones are the biggest problems.  Have you considered adding that to your code?

**Comment by m-manu** [comment]
@sanjosanjo Feature added in latest version.

**Comment by sanjosanjo** [comment]
You’re the best!  Thanks!
